version: '3.1'

services:
  postgres:
    image: postgres:16.0
    environment:
      POSTGRES_PASSWORD: pass123
    ports:
      - "5432:5432"
    volumes:
      - $HOME/docker-volumes/postgres/data:/var/lib/postgresql/data
